# Generated by Django 4.1.2 on 2022-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
