# Generated by Django 4.1.2 on 2022-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_documet_type_alter_document_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documet_type',
            new_name='document_type',
        ),
    ]
