# Generated by Django 4.0.7 on 2022-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_documet_type_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_data', models.TextField()),
            ],
        ),
    ]
