# Generated by Django 4.0.7 on 2022-12-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
