# Generated by Django 4.0.7 on 2022-12-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_delete_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document2',
            new_name='Document',
        ),
    ]
