# Generated by Django 4.0.7 on 2022-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_rename_document2_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='xml_data',
            field=models.FileField(upload_to=''),
        ),
    ]
