# Generated by Django 4.0.7 on 2022-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_xml_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='xml_data',
            field=models.TextField(),
        ),
    ]
